################################################################################
#Oracle Query Tool (via Pipeline)
#This tool can display full column names. For amount type fields, it can also
#display them completely, but for derived amount type fields, it may not.
#This can be resolved by using cast(amt+0.001 as number(15,3)).
#Supports executing multiple SQL statements simultaneously.
#Note: The linesize option in sqlplus has a significant impact on query
#performance; the larger the value, the slower the query.
#Author: Zang Jianwei
################################################################################
if [ $# -ne 2 -a $# -ne 4 ];then
	echo "Usage:$0 vimpid flag [username] [password]"
	exit
fi

if [ $# -eq 4 ];then
	DBUSER=$3
	DBPASS=$4
fi

lc_all=`locale|grep LC_all|awk -F"=" '{gsub(/"/, "", $2);print $2}'`

lc_utf_flag=`locale|grep LC_CTYPE|sed 's/"//g'|awk -F"=" '{print $2}'|awk -F. '{
		if (tolower($2) ~/utf/)
			print 1
		else
			print 0
	}'`

if [ $lc_utf_flag -eq 0 ];then
	if [ "$lc_all" != "" ];then
		export LC_ALL="$TUI_LC_CTYPE"
	else
		export LC_CTYPE="$TUI_LC_CTYPE"
	fi
fi

set -o noglob
#~/user/zjw/bin/regsql $1
#echo "test:$1"

#read_begin_flag=0
ReadPipe()
{
	while read -r line
	do
		#echo "line=[$line]"

		#Delete the clear_col_file generated by the last interrupted query.
		echo "$line"|grep SQL_END_ > /dev/null 2>&1
		if [ $? -eq 0 ];then
			clear_pid=`echo "$line"|sed 's/SQL_END_//g'`
			if [ "$clear_pid" != "$cur_pid" ];then
				rm -f $HOME/.dbtmp/${vimpid}_${clear_pid}_clearcol.col
				continue
			else
				#read_begin_flag=0
				break
			fi
		fi

		#if [[ "$line" = "$SQL_BEGIN" ]];then
		#	read_begin_flag=1
		#	continue
		#fi

		#if [[ "$read_begin_flag" != "1" ]];then
		#	continue
		#fi

		#if [[ "$line" = "$SQL_END" ]];then
		#	read_begin_flag=0
		#	break
		#fi
	done < $pipe_out 
}

vimpid=$1
pipe_in=~/.dbtmp/.pipe_in.$vimpid
pipe_out=~/.dbtmp/.pipe_out.$vimpid
sqlplus_pid_file=~/.dbtmp/.sqlplus_pid.$vimpid
browfile=~/.dbtmp/$vimpid.txt
#setfile=~/.dbtmp/${vimpid}_set.sql
sqlfile=~/.dbtmp/$vimpid.txt.sql
procfile=$HOME/.dbtmp/${vimpid}_proc.sql
descfile=$HOME/.dbtmp/$vimpid.desc
one_select_flag=$2
cur_pid=$$
#SQL_BEGIN=SQL_BEGIN_$cur_pid
SQL_END=SQL_END_$cur_pid

browfile=~/.dbtmp/$vimpid.txt

if [ ! -s $sqlfile ];then
	echo "No sql" > $browfile
	vim -c "set nonu" $browfile
	rm -f $browfile
	exit 3
fi

sql=`awk '{
	if (NR > 1)
		print prev_line
	prev_line = $0
	}
	END{
		gsub(/;[ \t]*$/, "", prev_line)
		print prev_line
	}' $sqlfile`

if [ ! -p $pipe_in ];then
	echo "Not connected to SQL*Plus" > $browfile
	vim -c "set nonu" $browfile
	rm -f $browfile
	rm -f $sqlfile
	exit 3
fi

sqlplus_pid=`cat $sqlplus_pid_file|awk '{print $1}'`
#pid2=`ps -ef|awk -v pid=$sqlplus_pid '{if ($2 == pid) print $2}'`
#if [ "$pid2" != "$sqlplus_pid" ];then
if ! kill -0 $sqlplus_pid 2>/dev/null; then
	echo "SQL*Plus connection closed" > $browfile
	vim -c "set nonu" $browfile
	rm -f $browfile
	rm -f $sqlfile
	exit 3
fi

kill_waitpid()
{
	#echo "pid $bg_pid is killed!"
	kill -9 $bg_pid 

	#The following line must be added; otherwise, issues will occur when executing again after an interruption.
	kill -INT $sqlplus_pid
	int_flag=1
}      

int_flag=0
trap "kill_waitpid" 2 3  

rotate()
{
	str[1]="-"
	str[2]="\\"
	str[3]="|"
	str[4]="/"
	clear     #Clear the screen.
	n=1
	while true
	do
	    #echo -e "\033[12;10H Executing SQL,You can press Ctrl+c to interrupt...${str[$n]}"
	    printf "\033[12;10H Executing SQL,You can press Ctrl+c to interrupt...${str[$n]} \n"
	    #echo -e "\033[24;5H Press Ctrl+c to interrupt"
		n=`echo $n|awk '{print ($0+1)%5}'`
	    if [ $n -eq 0 ]; then
	         n=1
	    fi
	    sleep 1
	done 
}

rotate &   
bg_pid=$!
#Remove from the job table;otherwise,it will be displayed.:31477 Killed rotate
if  command -v disown > /dev/null 2>&1 ;then
	disown $bg_pid
fi

if [ $one_select_flag -eq 1 ];then
	cat << EOF > $procfile
	set serveroutput on; 
	DECLARE 
	    c NUMBER; 
	    d NUMBER; 
	    col_cnt INTEGER; 
	    rec_tab DBMS_SQL.DESC_TAB; 
	    col_num NUMBER; 
	BEGIN 
	    c := DBMS_SQL.OPEN_CURSOR; 
	    DBMS_SQL.PARSE(c, q'[$sql]', DBMS_SQL.NATIVE);
	    d := DBMS_SQL.EXECUTE(c); 
	    DBMS_SQL.DESCRIBE_COLUMNS(c, col_cnt, rec_tab); 
	 
	    FOR col_num IN 1..col_cnt LOOP 
	        DBMS_OUTPUT.PUT_LINE(rec_tab(col_num).col_name||'@'||rec_tab(col_num).col_type||'@'||rec_tab(col_num).col_max_len||'@'||rec_tab(col_num).col_precision||'@'||rec_tab(col_num).col_scale||'@'||rec_tab(col_num).col_charsetform); 
	    END LOOP; 
	 
	    DBMS_SQL.CLOSE_CURSOR(c); 
	END; 
	/ 
EOF

	ReadPipe&
	read_pid=$!
	(
		#echo "store set $setfile"
		#echo "set echo off;"
		echo "SQL_START"
		#echo "prompt $SQL_BEGIN;"
		echo "set timing off;"
		echo "set linesize 80;"
		echo "set feedback off;"
		#echo "set numwidth 20;"
		#echo "set long 3000;"
		echo "set pagesize 200;"
		echo "set termout off;"
		#echo "set trimout on;"
		#echo "set heading on;"
		#echo "set trimspool on;"
		#echo "spool off;"
		#echo "exec dbms_output.put_line('SQL_START');" 
		echo "spool $descfile"
		echo "@$procfile"
		#echo "@$setfile;"
		echo "spool off;"
		echo "prompt $SQL_END;"
	) > $pipe_in

	wait $read_pid

	if [ $int_flag -eq 1 ];then
		echo "Request interrupted 2" > $browfile
		vim -c "set nonu"  $browfile
		rm -f $descfile
		rm -f $browfile
		#rm -f $setfile
		rm -f $procfile
		rm -f $sqlfile
		exit 3
	fi

	file_len=$HOME/.dbtmp/$vimpid.len
	set_col_file=$HOME/.dbtmp/${vimpid}_setcol.col
	clear_col_file=$HOME/.dbtmp/${vimpid}_${cur_pid}_clearcol.col
	>$set_col_file
	>$clear_col_file
	grep "^ORA-" $descfile > /dev/null 2>&1
	if [ $? -eq 0 ];then
		linesize=20000
	else
		cat $descfile|awk -v file_len=$file_len \
		                             -v set_col_file=$set_col_file \
									 -v clear_col_file=$clear_col_file  -F"@" '{ 
			if ($2 == 1 || $2 == 96) #char or varchar2/nchar or nvarchar2
			{
				arr_type[$1] = "C"

				if ($6 == 2)
				{
					#nchar/nvarchar2 The length must be multiplied by 2.
					$3 = $3*2
				}

				if (length($1) < $3) 
					max_len=$3;
				else 
					max_len=length($1);

				arr_max[$1] = max_len 

				$3 = max_len
			}
			else if ($2 == 2) #number
			{
				if ($4 > 0 && $5 > 0)
				{
					arr_type[$1] = "N"

					if (length($1) < $4 + 1) 
						max_len=$4 + 1;
					else 
						max_len=length($1);

					if (length($1) > max_len) 
						max_len=length($1);

					arr_tot_len[$1] = max_len 

					arr_last_len[$1] = $5
				}
				else
				{
					if (length($1) > $3) 
						max_len=length($1);
					else
						max_len=$3
				}

				$3 = max_len 
			}
			else if ($2 == 12) #date
			{
				$3 = 30

				if (length($1) > $3) 
					$3=length($1);
			}
			else if ($2 == 208) #urowid
			{
				$3 = 30
				arr_type[$1] = "C"

				if (length($1) > $3) 
					$3=length($1);

				arr_max[$1] = $3
			}
			else if ($2 == 180) #timestamp
			{
				$3 = 150
			}
			else if ($2 == 181) #timestamp with time zone
			{
				$3 = 200
			}
			else if ($2 == 231) #timestamp with local time zone
			{
				$3 = 200
			}
			else if ($2 == 23) #raw
			{
				$3 = $3*2

				if (length($1) > $3) 
					$3=length($1);
			}
			else if ($2 == 100) #binary_float
			{
				$3 = 30

				if (length($1) > $3) 
					$3=length($1);
			}
			else if ($2 == 101) #binary_double
			{
				$3 = 30

				if (length($1) > $3) 
					$3=length($1);
			}
			else if ($2 == 182) #interval year to month
			{
				$3 = 80
			}
			else if ($2 == 183) #interval day to second
			{
				$3 = 80
			}
			else if ($2 == 8) #long type $3 is 0
			{
				$3 = 1000
			}

			tot_len = tot_len + $3 + 2
		} 
		END { 
			for (colname in arr_type) 
			{
				#clear_str = ""
				clear_str = sprintf("column %s clear", colname)

				if (arr_type[colname] == "C")
				{
					#set_str = ""
					set_str = sprintf("column %s format a%d", colname, arr_max[colname] )
				}
				else
				{
					set_str = sprintf("column %s format ", colname)

					for (i=1;i<arr_tot_len[colname] - arr_last_len[colname]; i++)
					{
						set_str = sprintf("%s%d", set_str, 9)
					}
					set_str = sprintf("%s%s", set_str ,"0.")
					for (i=1;i<=arr_last_len[colname]; i++)
					{
						set_str = sprintf("%s%d", set_str , 9)
					}
					#set_str = sprintf("%s%s", set_str , "\n")
				}
				print set_str >> set_col_file
				print clear_str >> clear_col_file
			}
			#tot_len = tot_len + 100
			print tot_len > file_len
		}' 

		linesize=`cat $file_len`
	fi

	if [ $linesize -ge 32767 ];then
		linesize=32767
	fi

	ReadPipe&
	read_pid=$!
	(
		echo "SQL_START"
		#echo "prompt $SQL_BEGIN;"
		echo "@$set_col_file;"
		#echo "set echo off;"
		echo "set heading on;"
		echo "set feedback on;"
		echo "set timing on;"
		echo "set linesize $linesize;"
		#echo "set feedback on;"
		#echo "set numwidth 20;"
		#echo "set long 3000;"
		#echo "set termout off;"
		#echo "set trimout on;"
		#echo "set heading on;"
		#echo "set trimspool on;"
		echo "set pagesize 50000;"
		#echo "spool off;"
		#echo "exec dbms_output.put_line('SQL_START');" 
		echo "spool $browfile;"
		echo "@$sqlfile"
		#echo "$sqlstr"
		echo "spool off;"
		#The column settings must be restored, otherwise it will affect other queries.
		#If the SQL execution is interrupted (by pressing Ctrl+C), the following statements will also be executed.
		echo "@$clear_col_file;"  
		#Restore the set settings.
		#echo "@$setfile;"
		echo "prompt $SQL_END;"
	) > $pipe_in

	wait $read_pid
	
	#When interrupted, the ReadPipe must be killed; otherwise, the following situation may occur:
	#If the pipeline is interrupted while the query results have not yet arrived, they will not arrive until the next query.
	#If ReadPipe is not killed, both the old and new ReadPipe will read the pipeline simultaneously during the next query.
	#However, the pipeline is read based on the process ID. This can result in:
	#The old ReadPipe reading SQL_BEGIN and SQL_END from the new query,
	#while the new ReadPipe reads SQL_BEGIN and SQL_END from the old query,
	#causing the loop to never exit.

	if [ $int_flag -eq 1 ];then
		kill -9 $read_pid > /dev/null 2>&1
	else
		kill -9 $bg_pid   > /dev/null 2>&1
		rm -f $clear_col_file
	fi

	rm -f $procfile
	rm -f $descfile
	rm -f $set_col_file
	rm -f $file_len
else
	ReadPipe&
	read_pid=$!
	#if  command -v disown > /dev/null 2>&1 ;then
	#	disown $read_pid
	#fi

	(
		#echo "store set $setfile"
		echo "SQL_START"
		#echo "prompt $SQL_BEGIN;"
		echo "set heading on;"
		echo "set feedback on;"
		echo "set timing on;"
		echo "set linesize 10000;"
		echo "set pagesize 50000;"
		#echo "set feedback on;"
		#echo "spool off;"
		#echo "exec dbms_output.put_line('SQL_START');" 
		echo "spool $browfile;"
		echo "@$sqlfile;"
		#The set settings cannot be restored; otherwise, they will be restored after executing the set command.
		#echo "@$setfile;"
		echo "spool off;"
		echo "prompt $SQL_END;"
	) > $pipe_in

	wait $read_pid

	if [ $int_flag -eq 1 ];then
		kill -9 $read_pid > /dev/null 2>&1
	else
		kill -9 $bg_pid   > /dev/null 2>&1
	fi
fi

if [ ! -s $browfile ];then
	if [ $int_flag -ne 1 ];then
		echo "Execution completed" > $browfile
	else
		echo "Execution interrupted" > $browfile
	fi
	vim -c "set nonu" $browfile
else
	if [ $one_select_flag -eq 1 ];then
		suc_flag=`sed -n '3p' $browfile|awk '{if ($0 ~ /^[- ][- ]*$/) print 1}'`
		if [ "$suc_flag" = "1" ];then
			vim -u NONE -c "call oracle_tui#SetUsername('$DBUSER')|call oracle_tui#SetPassword('$DBPASS')|call oracle_tui#SetLocal()|call oracle_tui#ShowViewTitle()|call oracle_tui#SetMapView()|call oracle_tui#SetAutocmdView()|set ve=all|normal! gg" $browfile
		else
			vim -u NONE -c "call oracle_tui#SetLocal()" $browfile
		fi
	else
		vim -u NONE -c "call oracle_tui#SetLocal()|set ve=all" $browfile
	fi
fi

rm -f $browfile
#rm -f $setfile
rm -f $sqlfile


exit 0
